Repository YOG-yogi-odi-gym/yogi-odi-gym, pull requests merged in 2025-02, with the labels that each got.

#19 db: 초기 DB 셋팅
  src/main/resources/db/migration/V1__init.sql
Labels: db

#21 db: 초기 DB 셋팅2
  src/main/resources/db/migration/V2__drop_create_table.sql
  src/main/resources/db/migration/V3__data_insert.sql
Labels: chore, db

#24 db: 기존 마이그레이션 sql 수정
  src/main/resources/application.yml
  src/main/resources/db/migration/V1__init.sql
  src/main/resources/db/migration/V2__data_insert.sql
  src/main/resources/db/migration/V2__drop_create_table.sql
  src/main/resources/db/migration/V3__data_insert.sql
  src/test/resources/application.yml
Labels: db

#25 chore: Jasypt 설정
  build.gradle
  src/main/java/com/health/yogiodigym/config/JasyptConfig.java
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: chore

#28 CI/CD: Dockerfile 추가
  Dockerfile
Labels: CI/CD

#34 CI/CD: Github Actions 스크립트 수정
  .github/workflows/cicd.yml
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: CI/CD

#36 CI/CD: Dockerfile 수정
  Dockerfile
Labels: CI/CD

#40 chore: 회원 도메인 추가
  src/main/java/com/health/yogiodigym/member/auth/MemberStatus.java
  src/main/java/com/health/yogiodigym/member/auth/Role.java
  src/main/java/com/health/yogiodigym/member/entity/Member.java
  src/main/java/com/health/yogiodigym/member/repository/MemberRepository.java
  src/main/resources/db/migration/V3__create_authority.sql
Labels: chore, db

#46 feat: 공통으로 사용되는 표준 클래스 생성
  src/main/java/com/health/yogiodigym/common/exception/CustomException.java
  src/main/java/com/health/yogiodigym/common/exception/GlobalExceptionHandler.java
  src/main/java/com/health/yogiodigym/common/message/ErrorMessage.java
  src/main/java/com/health/yogiodigym/common/message/SuccessMessage.java
  src/main/java/com/health/yogiodigym/common/response/HttpResponse.java
Labels: feat

#41 feat: WebSocket/STOMP & Kafka를 연동한 채팅 기능 구현
  build.gradle
  src/main/java/com/health/yogiodigym/chat/config/ChatConstants.java
  src/main/java/com/health/yogiodigym/chat/config/KafkaConsumerConfiguration.java
  src/main/java/com/health/yogiodigym/chat/config/KafkaProducerConfiguration.java
  src/main/java/com/health/yogiodigym/chat/config/StompHandler.java
  src/main/java/com/health/yogiodigym/chat/config/StompWebSocketConfig.java
  src/main/java/com/health/yogiodigym/chat/controller/rest/StompController.java
  src/main/java/com/health/yogiodigym/chat/dto/MessageDto.java
  src/main/java/com/health/yogiodigym/chat/service/KafkaConsumerService.java
  src/main/java/com/health/yogiodigym/chat/service/KafkaProducerService.java
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: feat

#52 bug: ExceptionHandler 수정
  src/main/java/com/health/yogiodigym/common/exception/GlobalExceptionHandler.java
Labels: bug

#44 feat: 회원 전체조회 / 검색 기능 구현
  src/main/java/com/health/yogiodigym/YogiOdiGymApplication.java
  src/main/java/com/health/yogiodigym/admin/controller/AdminController.java
  src/main/java/com/health/yogiodigym/admin/controller/AdminViewController.java
  src/main/java/com/health/yogiodigym/admin/dto/MemberDto.java
  src/main/java/com/health/yogiodigym/admin/service/AdminService.java
  src/main/java/com/health/yogiodigym/admin/service/impl/AdminServiceImpl.java
  src/main/java/com/health/yogiodigym/common/message/SuccessMessage.java
  src/main/java/com/health/yogiodigym/common/response/HttpResponse.java
  src/main/java/com/health/yogiodigym/member/auth/MemberStatus.java
  src/main/java/com/health/yogiodigym/member/repository/MemberRepository.java
  src/main/resources/templates/admin.html
  src/test/java/com/health/yogiodigym/member/service/MemberServiceTest.java
Labels: feat

#58 feat: 채팅방 기능 구현
  build.gradle
  src/main/java/com/health/yogiodigym/chat/config/ChatConstants.java
  src/main/java/com/health/yogiodigym/chat/config/KafkaConsumerConfiguration.java
  src/main/java/com/health/yogiodigym/chat/config/KafkaProducerConfiguration.java
  src/main/java/com/health/yogiodigym/chat/controller/rest/ChatRoomController.java
  src/main/java/com/health/yogiodigym/chat/controller/rest/StompController.java
  src/main/java/com/health/yogiodigym/chat/dto/ChatRoomDto.java
  src/main/java/com/health/yogiodigym/chat/dto/MessageDto.java
  src/main/java/com/health/yogiodigym/chat/entity/ChatMessage.java
  src/main/java/com/health/yogiodigym/chat/entity/ChatParticipant.java
  src/main/java/com/health/yogiodigym/chat/entity/ChatReadStatus.java
  src/main/java/com/health/yogiodigym/chat/entity/ChatRoom.java
  src/main/java/com/health/yogiodigym/chat/repository/ChatMessageRepository.java
  src/main/java/com/health/yogiodigym/chat/repository/ChatParticipantRepository.java
  src/main/java/com/health/yogiodigym/chat/repository/ChatReadStatusRepository.java
  src/main/java/com/health/yogiodigym/chat/repository/ChatRoomRepository.java
  src/main/java/com/health/yogiodigym/chat/service/ChatRoomService.java
  src/main/java/com/health/yogiodigym/chat/service/KafkaProducerService.java
  src/main/java/com/health/yogiodigym/chat/service/impl/ChatRoomServiceImpl.java
  src/main/java/com/health/yogiodigym/common/entity/BaseTimeEntity.java
  src/main/java/com/health/yogiodigym/common/exception/AlreadyChatParticipantException.java
  src/main/java/com/health/yogiodigym/common/exception/ChatRoomNotFoundException.java
  src/main/java/com/health/yogiodigym/common/exception/MemberNotFoundException.java
  src/main/java/com/health/yogiodigym/common/exception/MemberNotInChatRoomException.java
  src/main/java/com/health/yogiodigym/common/message/ErrorMessage.java
  src/main/java/com/health/yogiodigym/common/message/SuccessMessage.java
  src/main/java/com/health/yogiodigym/config/JpaConfig.java
  src/main/java/com/health/yogiodigym/lesson/entity/Category.java
  src/main/java/com/health/yogiodigym/lesson/entity/Lesson.java
  src/main/java/com/health/yogiodigym/lesson/entity/LessonEnrollment.java
  src/main/java/com/health/yogiodigym/lesson/repository/CategoryRepository.java
  src/main/java/com/health/yogiodigym/lesson/repository/LessonEnrollmentRepository.java
  src/main/java/com/health/yogiodigym/lesson/repository/LessonRepository.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/com/health/yogiodigym/chat/controller/rest/ChatRoomControllerTest.java
  src/test/java/com/health/yogiodigym/chat/repository/ChatMessageRepositoryTest.java
  src/test/java/com/health/yogiodigym/chat/repository/ChatParticipantRepositoryTest.java
  src/test/java/com/health/yogiodigym/chat/repository/ChatRoomRepositoryTest.java
  src/test/java/com/health/yogiodigym/chat/service/ChatRoomServiceTest.java
  src/test/java/com/health/yogiodigym/lesson/repository/LessonEnrollmentRepositoryTest.java
  src/test/java/com/health/yogiodigym/lesson/repository/LessonRepositoryTest.java
  src/test/java/com/health/yogiodigym/util/TestSecurityConfig.java
  src/test/java/com/health/yogiodigym/util/WithCustomMockUser.java
  src/test/java/com/health/yogiodigym/util/WithCustomMockUserSecurityContextFactory.java
Labels: feat, refactor

#66 bug: 채팅방 생성 서비스 로직 수정
  src/main/java/com/health/yogiodigym/chat/service/ChatRoomService.java
  src/main/java/com/health/yogiodigym/chat/service/impl/ChatRoomServiceImpl.java
Labels: bug

#59 feat: 헬스장 찾기, 강의 구현
  src/main/java/com/health/yogiodigym/common/exception/CategoryNotFoundException.java
  src/main/java/com/health/yogiodigym/common/exception/LessonEnrollmentException.java
  src/main/java/com/health/yogiodigym/common/exception/LessonNotFoundException.java
  src/main/java/com/health/yogiodigym/common/message/ErrorMessage.java
  src/main/java/com/health/yogiodigym/common/message/SuccessMessage.java
  src/main/java/com/health/yogiodigym/gym/controller/GymController.java
  src/main/java/com/health/yogiodigym/gym/controller/GymViewController.java
  src/main/java/com/health/yogiodigym/gym/dto/DataGymDto.java
  src/main/java/com/health/yogiodigym/gym/entity/DataGym.java
  src/main/java/com/health/yogiodigym/gym/repository/GymRepository.java
  src/main/java/com/health/yogiodigym/gym/service/GymService.java
  src/main/java/com/health/yogiodigym/gym/service/impl/GymServiceImpl.java
  src/main/java/com/health/yogiodigym/lesson/controller/LessonController.java
  src/main/java/com/health/yogiodigym/lesson/controller/LessonViewController.java
  src/main/java/com/health/yogiodigym/lesson/dto/CategoryDto.java
  src/main/java/com/health/yogiodigym/lesson/dto/LessonDto.java
  src/main/java/com/health/yogiodigym/lesson/dto/MemberLatLonDto.java
  src/main/java/com/health/yogiodigym/lesson/entity/Category.java
  src/main/java/com/health/yogiodigym/lesson/entity/Lesson.java
  src/main/java/com/health/yogiodigym/lesson/entity/LessonEnrollment.java
  src/main/java/com/health/yogiodigym/lesson/repository/CategoryRepository.java
  src/main/java/com/health/yogiodigym/lesson/repository/LessonEnrollmentRepository.java
  src/main/java/com/health/yogiodigym/lesson/repository/LessonRepository.java
  src/main/java/com/health/yogiodigym/lesson/service/LessonEnrollmentService.java
  src/main/java/com/health/yogiodigym/lesson/service/LessonService.java
  src/main/java/com/health/yogiodigym/lesson/service/impl/LessonEnrollmentServiceImpl.java
  src/main/java/com/health/yogiodigym/lesson/service/impl/LessonServiceImpl.java
  src/main/java/com/health/yogiodigym/member/config/SecurityConfig.java
  src/main/resources/static/js/LatLonApi.js
  src/main/resources/static/js/bitmaskToDays.js
  src/main/resources/static/js/gymSearch.js
  src/main/resources/static/js/lessonDetail.js
  src/main/resources/static/js/lessonRegister.js
  src/main/resources/static/js/lessonSearch.js
  src/main/resources/static/js/lessonValidateDate.js
  src/main/resources/templates/gym/gyms.html
  src/main/resources/templates/lesson/detail.html
  src/main/resources/templates/lesson/edit.html
  src/main/resources/templates/lesson/lesson.html
  src/main/resources/templates/lesson/register.html
  src/main/resources/templates/member/regist.html
Labels: feat

#70 feat: 관리자 강의 삭제 및 UI 업데이
  src/main/resources/db/migration/V4__create_chat.sql
  src/main/resources/templates/admin.html
Labels: bug, db

#75 cicd: 도커 실행 명령어 수정
  .github/workflows/cicd.yml
Labels: CI/CD
