Repository YOG-yogi-odi-gym/yogi-odi-gym, pull requests merged in 2025-03, with the labels that each got.

#82 feat: 레디스 세션 추가
  build.gradle
  src/main/java/com/health/yogiodigym/config/RedisConfig.java
  src/main/java/com/health/yogiodigym/member/controller/view/MainViewController.java
  src/main/java/com/health/yogiodigym/member/controller/view/MemberViewController.java
  src/main/java/com/health/yogiodigym/member/entity/Member.java
  src/main/java/com/health/yogiodigym/member/service/OAuth2UserService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/main/resources/static/js/LatLonApi.js
  src/test/resources/application.yml
Labels: feat

#89 feat: 채팅 화면 구현
  src/main/java/com/health/yogiodigym/chat/config/ChatConstants.java
  src/main/java/com/health/yogiodigym/chat/config/StompHandler.java
  src/main/java/com/health/yogiodigym/chat/config/StompWebSocketConfig.java
  src/main/java/com/health/yogiodigym/chat/config/WebSocketHandshakeInterceptor.java
  src/main/java/com/health/yogiodigym/chat/controller/rest/ChatMessageController.java
  src/main/java/com/health/yogiodigym/chat/controller/view/ChatViewController.java
  src/main/java/com/health/yogiodigym/chat/dto/MessageDto.java
  src/main/java/com/health/yogiodigym/chat/repository/ChatMessageRepository.java
  src/main/java/com/health/yogiodigym/chat/service/ChatMessageService.java
  src/main/java/com/health/yogiodigym/chat/service/ChatRoomService.java
  src/main/java/com/health/yogiodigym/chat/service/impl/ChatMessageServiceImpl.java
  src/main/java/com/health/yogiodigym/chat/service/impl/ChatRoomServiceImpl.java
  src/main/java/com/health/yogiodigym/common/message/SuccessMessage.java
  src/main/java/com/health/yogiodigym/lesson/repository/LessonRepository.java
  src/main/resources/static/css/chat/chat.css
  src/main/resources/static/js/chat/chat.js
  src/main/resources/templates/chat/chat.html
  src/test/java/com/health/yogiodigym/chat/repository/ChatMessageRepositoryTest.java
  src/test/java/com/health/yogiodigym/chat/service/impl/ChatMessageServiceTest.java
Labels: feat

#73 feat : 사이드바
  src/main/java/com/health/yogiodigym/member/controller/view/MemberViewController.java
  src/main/resources/static/css/lessonSearch.css
  src/main/resources/static/images/source/yogi_side_img.jpg
  src/main/resources/templates/dashboard.html
  src/main/resources/templates/fragments/side.html
Labels: feat

#47 feat: 캘린더 기능 구현
  src/main/java/com/health/yogiodigym/calendar/controller/CalendarExerciseController.java
  src/main/java/com/health/yogiodigym/calendar/controller/CalendarFoodController.java
  src/main/java/com/health/yogiodigym/calendar/controller/CalendarLessonController.java
  src/main/java/com/health/yogiodigym/calendar/controller/CalendarMemoController.java
  src/main/java/com/health/yogiodigym/calendar/controller/CalendarViewController.java
  src/main/java/com/health/yogiodigym/calendar/controller/DataExerciseController.java
  src/main/java/com/health/yogiodigym/calendar/controller/DataFoodController.java
  src/main/java/com/health/yogiodigym/calendar/dto/CalendarExerciseDto.java
  src/main/java/com/health/yogiodigym/calendar/dto/CalendarFoodDto.java
  src/main/java/com/health/yogiodigym/calendar/dto/CalendarLessonDto.java
  src/main/java/com/health/yogiodigym/calendar/dto/CalendarMemberDto.java
  src/main/java/com/health/yogiodigym/calendar/dto/CalendarMemoDto.java
  src/main/java/com/health/yogiodigym/calendar/dto/DataExerciseDto.java
  src/main/java/com/health/yogiodigym/calendar/dto/DataFoodDto.java
  src/main/java/com/health/yogiodigym/calendar/entity/CalendarExercise.java
  src/main/java/com/health/yogiodigym/calendar/entity/CalendarFood.java
  src/main/java/com/health/yogiodigym/calendar/entity/CalendarMemo.java
  src/main/java/com/health/yogiodigym/calendar/entity/DataExercise.java
  src/main/java/com/health/yogiodigym/calendar/entity/DataFood.java
  src/main/java/com/health/yogiodigym/calendar/repository/CalendarExerciseRepository.java
  src/main/java/com/health/yogiodigym/calendar/repository/CalendarFoodRepository.java
  src/main/java/com/health/yogiodigym/calendar/repository/CalendarMemoRepository.java
  src/main/java/com/health/yogiodigym/calendar/repository/DataExerciseRepository.java
  src/main/java/com/health/yogiodigym/calendar/repository/DataFoodRepository.java
  src/main/java/com/health/yogiodigym/calendar/service/CalendarExerciseService.java
  src/main/java/com/health/yogiodigym/calendar/service/CalendarFoodService.java
  src/main/java/com/health/yogiodigym/calendar/service/CalendarLessonService.java
  src/main/java/com/health/yogiodigym/calendar/service/CalendarMemoService.java
  src/main/java/com/health/yogiodigym/calendar/service/DataExerciseService.java
  src/main/java/com/health/yogiodigym/calendar/service/DataFoodService.java
  src/main/java/com/health/yogiodigym/calendar/service/impl/CalendarExerciseServiceImpl.java
  src/main/java/com/health/yogiodigym/calendar/service/impl/CalendarFoodServiceImpl.java
  src/main/java/com/health/yogiodigym/calendar/service/impl/CalendarLessonServiceImpl.java
  src/main/java/com/health/yogiodigym/calendar/service/impl/CalendarMemoServiceImpl.java
  src/main/java/com/health/yogiodigym/calendar/service/impl/DataExerciseServiceImpl.java
  src/main/java/com/health/yogiodigym/calendar/service/impl/DataFoodServiceImpl.java
  src/main/java/com/health/yogiodigym/common/exception/DataExerciseNotFoundException.java
  src/main/java/com/health/yogiodigym/common/exception/DataFoodNotFoundException.java
  src/main/java/com/health/yogiodigym/common/exception/ExerciseNotFoundException.java
  src/main/java/com/health/yogiodigym/common/exception/FoodNotFoundException.java
  src/main/java/com/health/yogiodigym/common/exception/MemoNotFoundException.java
  src/main/java/com/health/yogiodigym/common/message/ErrorMessage.java
  src/main/java/com/health/yogiodigym/common/message/SuccessMessage.java
  src/main/java/com/health/yogiodigym/member/controller/view/MainViewController.java
  src/main/resources/static/css/calendar/calendar.css
  src/main/resources/static/js/calendar/calculate.js
  src/main/resources/static/js/calendar/filter_action.js
  src/main/resources/templates/calendar/cal.html
  src/main/resources/templates/calendar/select_exercise.html
  src/main/resources/templates/calendar/select_food.html
Labels: feat

#101 Feat#98 강의, 채팅 기능 연동
  src/main/java/com/health/yogiodigym/board/controller/BoardController.java
  src/main/java/com/health/yogiodigym/board/dto/BoardDto.java
  src/main/java/com/health/yogiodigym/board/repository/CommentRepository.java
  src/main/java/com/health/yogiodigym/lesson/controller/LessonController.java
  src/main/java/com/health/yogiodigym/lesson/dto/LessonDto.java
  src/main/java/com/health/yogiodigym/lesson/repository/LessonRepository.java
  src/main/java/com/health/yogiodigym/lesson/service/LessonService.java
  src/main/java/com/health/yogiodigym/lesson/service/impl/LessonEnrollmentServiceImpl.java
  src/main/java/com/health/yogiodigym/lesson/service/impl/LessonServiceImpl.java
  src/main/resources/static/js/gymSearch.js
  src/main/resources/static/js/lesson/bitmaskToDays.js
  src/main/resources/static/js/lesson/latLonApi.js
  src/main/resources/static/js/lesson/lessonRegister.js
  src/main/resources/static/js/lesson/lessonValidateDate.js
  src/main/resources/static/js/lessonDetail.js
  src/main/resources/static/js/lessonSearch.js
  src/main/resources/templates/board/detail.html
  src/main/resources/templates/lesson/detail.html
  src/main/resources/templates/lesson/edit.html
  src/main/resources/templates/lesson/register.html
  src/main/resources/templates/member/regist.html
Labels: feat

#102 bug: 로그인 버그 수정
  src/main/java/com/health/yogiodigym/member/entity/MemberOAuth2User.java
  src/main/java/com/health/yogiodigym/member/service/impl/MemberServiceImpl.java
  src/main/java/com/health/yogiodigym/member/service/impl/NCPStorageServiceImpl.java
Labels: bug

#103 feat: 대시보드 인기게시글, 채팅방 목록 조회 기능 구현
  src/main/java/com/health/yogiodigym/board/dto/BoardDto.java
  src/main/java/com/health/yogiodigym/board/repository/BoardRepository.java
  src/main/java/com/health/yogiodigym/board/service/BoardService.java
  src/main/java/com/health/yogiodigym/board/service/impl/BoardServiceImpl.java
  src/main/java/com/health/yogiodigym/chat/dto/ChatRoomDto.java
  src/main/java/com/health/yogiodigym/chat/entity/ChatParticipant.java
  src/main/java/com/health/yogiodigym/chat/service/impl/ChatMessageServiceImpl.java
  src/main/java/com/health/yogiodigym/chat/service/impl/ChatRoomServiceImpl.java
  src/main/java/com/health/yogiodigym/member/controller/view/MainViewController.java
  src/main/resources/templates/chat/chat.html
  src/test/java/com/health/yogiodigym/chat/service/ChatRoomServiceTest.java
  src/test/java/com/health/yogiodigym/chat/service/impl/ChatMessageServiceTest.java
Labels: feat

#112 feat: 대시보드 운동량, 칼로리 조회 기능 구현
  src/main/java/com/health/yogiodigym/calendar/repository/CalendarExerciseRepository.java
  src/main/java/com/health/yogiodigym/member/controller/view/MainViewController.java
  src/main/java/com/health/yogiodigym/member/entity/GraphAverage.java
  src/main/java/com/health/yogiodigym/member/repository/GraphAverageRepository.java
  src/main/java/com/health/yogiodigym/member/service/GraphAverageService.java
  src/main/java/com/health/yogiodigym/member/service/impl/GraphAverageServiceImpl.java
  src/main/resources/db/migration/V7__alter_graph_average.sql
Labels: feat

#122 bug: 안읽은 메시지 ID 기본값 추가 및 메시지 수신시 메시지 저장 버그 해결
  src/main/java/com/health/yogiodigym/chat/config/KafkaConsumerConfiguration.java
  src/main/java/com/health/yogiodigym/chat/config/KafkaProducerConfiguration.java
  src/main/java/com/health/yogiodigym/chat/controller/rest/StompController.java
  src/main/java/com/health/yogiodigym/chat/service/KafkaConsumerService.java
  src/main/java/com/health/yogiodigym/chat/service/KafkaProducerService.java
  src/main/java/com/health/yogiodigym/chat/service/impl/ChatRoomServiceImpl.java
  src/main/resources/static/css/chat/chat.css
  src/test/java/com/health/yogiodigym/chat/service/ChatRoomServiceTest.java
Labels: bug

#125 기능 수정 및 UI 수정
  src/main/java/com/health/yogiodigym/board/dto/CommentDto.java
  src/main/java/com/health/yogiodigym/board/entity/Comment.java
  src/main/resources/static/js/lesson/lessonValidateDate.js
  src/main/resources/templates/board/board.html
  src/main/resources/templates/board/detail.html
  src/main/resources/templates/board/edit.html
  src/main/resources/templates/board/register.html
  src/main/resources/templates/gym/gyms.html
  src/main/resources/templates/lesson/detail.html
  src/main/resources/templates/lesson/edit.html
  src/main/resources/templates/lesson/lesson.html
  src/main/resources/templates/lesson/register.html
  src/main/resources/templates/my/board.html
  src/main/resources/templates/my/lesson.html
  src/main/resources/templates/navi/header.html
  src/main/resources/templates/navi/sidebar.html
Labels: bug

#129 refactor: 채팅 화면 수정
  src/main/resources/static/css/chat/chat.css
  src/main/resources/templates/chat/chat.html
Labels: refactor

#131 검색 결과 수정
  src/main/java/com/health/yogiodigym/board/service/impl/BoardServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/templates/fragments/side.html
Labels: bug

#133 검색 결과 안내
  src/main/resources/templates/board/board.html
  src/main/resources/templates/gym/gyms.html
  src/main/resources/templates/lesson/lesson.html
  src/main/resources/templates/my/board.html
  src/main/resources/templates/my/lesson.html
Labels: feat

#138 bug: 로그인 실패 예외메시지 오류 수정
  src/main/java/com/health/yogiodigym/config/SecurityConfig.java
Labels: bug

#139 feat: 채팅 강퇴 추가 및 버그 수정
  src/main/java/com/health/yogiodigym/chat/dto/ChatParticipantDto.java
  src/main/java/com/health/yogiodigym/chat/dto/ChatRoomDto.java
  src/main/java/com/health/yogiodigym/chat/service/impl/ChatParticipantServiceImpl.java
  src/main/java/com/health/yogiodigym/chat/service/impl/ChatRoomServiceImpl.java
  src/main/java/com/health/yogiodigym/common/exception/ForbiddenException.java
  src/main/java/com/health/yogiodigym/common/exception/KickInstructorException.java
  src/main/java/com/health/yogiodigym/common/exception/MemberNotInLessonException.java
  src/main/java/com/health/yogiodigym/common/message/ErrorMessage.java
  src/main/java/com/health/yogiodigym/config/RedisConfig.java
  src/main/resources/static/css/chat/chat.css
  src/main/resources/static/js/chat/chat.js
  src/main/resources/templates/chat/chat.html
  src/test/java/com/health/yogiodigym/chat/service/ChatRoomServiceTest.java
Labels: bug, feat

#144 refactor: 회원가입 코드컨벤션 맞춰서 리펙터링
  src/main/java/com/health/yogiodigym/admin/service/impl/AdminMemberToMasterServiceImpl.java
  src/main/java/com/health/yogiodigym/common/exception/PasswordEmptyException.java
  src/main/java/com/health/yogiodigym/common/message/ErrorMessage.java
  src/main/java/com/health/yogiodigym/member/entity/Member.java
  src/main/java/com/health/yogiodigym/member/repository/MemberRepository.java
  src/main/java/com/health/yogiodigym/member/service/impl/MemberServiceImpl.java
  src/main/java/com/health/yogiodigym/my/controller/rest/MyController.java
  src/main/java/com/health/yogiodigym/my/entity/MemberToMaster.java
  src/main/java/com/health/yogiodigym/my/repository/MemberToMasterRepository.java
Labels: refactor

#145 refactor : 캘린더 UI 2차 변경
  src/main/resources/static/js/calendar/filter_action.js
  src/main/resources/templates/calendar/select_exercise.html
  src/main/resources/templates/calendar/select_food.html
Labels: refactor

#159 bug: 채팅 메시지 버그 수정
  src/main/java/com/health/yogiodigym/chat/controller/view/ChatViewController.java
  src/main/java/com/health/yogiodigym/chat/repository/ChatMessageRepository.java
  src/main/java/com/health/yogiodigym/chat/service/ChatMessageService.java
  src/main/java/com/health/yogiodigym/chat/service/impl/ChatMessageServiceImpl.java
  src/main/resources/static/js/chat/chat.js
Labels: bug

#160 cicd: 도커 배포 컨테이너 시간대 조정
  Dockerfile
Labels: CI/CD

#156 fix : 이벤트 흰색 안나오도록 색상수정, 데이터 검색창 css 변경
  src/main/resources/static/js/calendar/filter_action.js
  src/main/resources/templates/calendar/select_exercise.html
  src/main/resources/templates/calendar/select_food.html
Labels: bug

#157 bug: 동일한 비밀번호로 수정 방지
  src/main/java/com/health/yogiodigym/common/exception/AlreadyEnrollMasterException.java
  src/main/java/com/health/yogiodigym/common/exception/BeforePwdMatchException.java
  src/main/java/com/health/yogiodigym/common/message/ErrorMessage.java
  src/main/java/com/health/yogiodigym/member/service/impl/MemberServiceImpl.java
  src/main/resources/templates/fragments/navbar.html
  src/main/resources/templates/my/info.html
Labels: bug

#163 refactor: 컨벤션에 맞춰서 리펙터링
  src/main/java/com/health/yogiodigym/member/service/impl/MemberServiceImpl.java
  src/main/resources/templates/gym/gyms.html
  src/main/resources/templates/member/find_pwd.html
Labels: refactor

#166 bug: 헬스창 찾기 페이징 넘버링 오류 수정
  src/main/resources/templates/gym/gyms.html
Labels: bug

#168 Bug: 버그 수정
  src/main/resources/application.yml
  src/main/resources/static/css/chat/chat.css
  src/main/resources/static/js/dashboard.js
Labels: bug
